name: imlo-coursework
channels:
    - defaults
dependencies:
    - python=3.11
    - pip
    - pip:
        - matplotlib
        - numpy
        - pillow
        - pandas
        - scikit-learn
        - scipy
        - seaborn
        - torch
        - torchinfo
        - torchvision
        - tqdm
